#!/usr/bin/env bash

# Usage
# ./roverctl ssh_host_name restart_server

user_env_var_on_remote_host=$(ssh ${ssh_remote_host} printenv | grep USER=)
user=${user_env_var_on_remote_host:5}

ssh_remote_host=$1
cmd=$2

if [ -z "${ssh_remote_host}" ]; then
    echo "Specify an ssh host defined in ~/.ssh/config as the first argument"
    exit 1
fi

if [ "${cmd}" = "restart_server" ]; then
  ssh ${ssh_remote_host} "/home/${user}/nyanko-rover-server/server_utils/restart_server.sh"
elif [ "${cmd}" = "stop_server" ]; then
  ssh ${ssh_remote_host} "/home/${user}/nyanko-rover-server/server_utils/stop_server.sh"
elif [ "${cmd}" = "tail-log" ]; then
  ssh ${ssh_remote_host} "tail -f /home/${user}/nyanko-rover-server/nyankoroverserver.log"
elif [ "${cmd}" = "view-log" ]; then
  rsync ${ssh_remote_host}:/home/${user}/nyanko-rover-server/nyankoroverserver.log ./
  code nyankoroverserver.log
elif [ "${cmd}" = "shutdown" ]; then
  ssh ${ssh_remote_host} "sudo shutdown now"
elif [ "${cmd}" = "reboot" ]; then
  ssh ${ssh_remote_host} "sudo reboot now"
fi
